-- This file contains SQL commands to set up the database environment for the Oracle Weather Project.

-- Create a type for representing a city
CREATE OR REPLACE TYPE city_type AS OBJECT (
    city_name VARCHAR2(100),
    country VARCHAR2(100)
);

-- Create a table to store weather information
CREATE TABLE weather_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city city_type,
    temperature NUMBER,
    humidity NUMBER,
    description VARCHAR2(255),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert initial data (example)
INSERT INTO weather_data (city, temperature, humidity, description) VALUES 
    (city_type('San Francisco', 'USA'), 15, 60, 'Clear sky'),
    (city_type('New York', 'USA'), 22, 50, 'Partly cloudy');